# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
 IISWebsiteName: 'AzureTestProject'

resources:
 pipelines:
     - pipeline: 'buildPipeline'
       project: 'AzureTestProject'
       source: 'Build Pipeline'
       branch: 'main'

stages:
    - stage: 'DeployWebsite'
      displayName: 'Deploy Website'
      pool: 'MyComputerAgent'

      jobs:
          - deployment: 'DeployWebsite'
            displayName: 'Deploy Website'
            environment: 'AzureDeployment.DESKTOP-6O4J0HA'
            strategy:
             runOnce:
              deploy:
               steps:
                   - checkout: none

                   - download: 'buildPipeline'
                     name: 'DownloadBuildArtifacts'
                     displayName: 'Download Build Artifacts'
                     artifact: 'AzureTestProject'
                 
                   - task: IISWebAppManagementOnMachineGroup@0
                     name: 'StopIIS'
                     displayName: 'Stop IIS Website'
                     inputs:
                       IISDeploymentType: 'IISWebsite'
                       ActionIISWebsite: 'StopWebsite'
                       StartStopWebsiteName: '${{ variables.IISWebsiteName }}'

                   - task: IISWebAppDeploymentOnMachineGroup@0
                     name: 'DeployIIS'
                     displayName: 'Deploy IIS Website'
                     inputs:
                       WebSiteName: '${{ variables.IISWebsiteName }}'
                       Package: '$(Pipeline.Workspace)\AzureTestProject\Devops.WebApi'
                       TakeAppOfflineFlag: true
                
                   - task: IISWebAppManagementOnMachineGroup@0
                     name: 'StartIIS'
                     displayName: 'Start IIS Website'
                     inputs:
                       IISDeploymentType: 'IISWebsite'
                       ActionIISWebsite: 'StartWebsite'
                       StartStopWebsiteName: '${{ variables.IISWebsiteName }}'
                    
                     
                
                
                  
